---
title: "combine_protax_output_tables"
author: "Douglas Yu"
date: "19/05/2019"
output: html_document
---

2 outputs
    w_protaxout_swarm_12S
    w_protaxout_swarm_16S
5 or 7 column headings
"queryID", "taxID", "log_prob", "level", "taxon", "bestHit_similarity", "bestHit"

```{r}
library(tidyverse)
```

```{r}
# rm(list = ls())
```

```{r combine weighted swarm_12S}
pathtoprotaxout <- "~/src/screenforbio-mbc-ailaoshan"
pathtoprotax2 <- "w_protaxout_swarm_12S"
pathtoprotax_file <- "all_12S_20180317_otu_table_swarm_lulu."
# setwd(pathtoprotaxout)
w_protaxout_swarm_12S_class <- read_tsv(file.path(pathtoprotaxout, pathtoprotax2, paste0(pathtoprotax_file, "w_class_probs")), col_names = c("queryID", "taxID", "log_prob", "level", "class")) %>% 
    mutate(prob_class = exp(log_prob)) %>% 
    select(queryID, class, prob_class)
w_protaxout_swarm_12S_order <- read_tsv(file.path(pathtoprotaxout, pathtoprotax2, paste0(pathtoprotax_file, "w_order_probs")), col_names = c("queryID", "taxID", "log_prob", "level", "order")) %>% 
    mutate(prob_order = exp(log_prob)) %>% 
    select(queryID, order, prob_order)
w_protaxout_swarm_12S_family <- read_tsv(file.path(pathtoprotaxout, pathtoprotax2, paste0(pathtoprotax_file, "w_family_probs")), col_names = c("queryID", "taxID", "log_prob", "level", "family")) %>% 
    mutate(prob_family = exp(log_prob)) %>% 
    select(queryID, family, prob_family)
w_protaxout_swarm_12S_genus <- read_tsv(file.path(pathtoprotaxout, pathtoprotax2, paste0(pathtoprotax_file, "w_genus_probs")), col_names = c("queryID", "taxID", "log_prob", "level", "genus")) %>% 
    mutate(prob_genus = exp(log_prob)) %>% 
    select(queryID, genus, prob_genus)
w_protaxout_swarm_12S_species <- read.delim(file.path(pathtoprotaxout, pathtoprotax2, paste0(pathtoprotax_file, "w_species_probs_sim")), stringsAsFactors = FALSE, sep = " ", col.names = c("queryID", "taxID", "log_prob", "level", "species", "bestHit_similarity", "bestHit")) %>% 
    mutate(prob_species = exp(log_prob)) %>% 
    mutate(taxID = na_if(taxID, "")) %>% 
    mutate(species = na_if(species, "")) %>% 
    select(queryID, species, prob_species, bestHit_similarity, bestHit)

w_protaxout_swarm_12S_all <- w_protaxout_swarm_12S_class %>% 
    left_join(w_protaxout_swarm_12S_order) %>% 
    left_join(w_protaxout_swarm_12S_family) %>% 
    left_join(w_protaxout_swarm_12S_genus) %>% 
    left_join(w_protaxout_swarm_12S_species) 
w_protaxout_swarm_12S_all$protaxmod <- "weighted"

```

```{r combine unweighted swarm_12S}
pathtoprotaxout <- "~/src/screenforbio-mbc-ailaoshan"
pathtoprotax2 <- "protaxout_swarm_12S"
pathtoprotax_file <- "all_12S_20180317_otu_table_swarm_lulu."
# setwd(pathtoprotaxout)
protaxout_swarm_12S_class <- read_tsv(file.path(pathtoprotaxout, pathtoprotax2, paste0(pathtoprotax_file, "class_probs")), col_names = c("queryID", "taxID", "log_prob", "level", "class")) %>% 
    mutate(prob_class = exp(log_prob)) %>% 
    select(queryID, class, prob_class)
protaxout_swarm_12S_order <- read_tsv(file.path(pathtoprotaxout, pathtoprotax2, paste0(pathtoprotax_file, "order_probs")), col_names = c("queryID", "taxID", "log_prob", "level", "order")) %>% 
    mutate(prob_order = exp(log_prob)) %>% 
    select(queryID, order, prob_order)
protaxout_swarm_12S_family <- read_tsv(file.path(pathtoprotaxout, pathtoprotax2, paste0(pathtoprotax_file, "family_probs")), col_names = c("queryID", "taxID", "log_prob", "level", "family")) %>% 
    mutate(prob_family = exp(log_prob)) %>% 
    select(queryID, family, prob_family)
protaxout_swarm_12S_genus <- read_tsv(file.path(pathtoprotaxout, pathtoprotax2, paste0(pathtoprotax_file, "genus_probs")), col_names = c("queryID", "taxID", "log_prob", "level", "genus")) %>% 
    mutate(prob_genus = exp(log_prob)) %>% 
    select(queryID, genus, prob_genus)
protaxout_swarm_12S_species <- read.delim(file.path(pathtoprotaxout, pathtoprotax2, paste0(pathtoprotax_file, "species_probs_sim")), stringsAsFactors = FALSE, sep = " ", col.names = c("queryID", "taxID", "log_prob", "level", "species", "bestHit_similarity", "bestHit")) %>% 
    mutate(prob_species = exp(log_prob)) %>% 
    mutate(taxID = na_if(taxID, "")) %>% 
    mutate(species = na_if(species, "")) %>% 
    select(queryID, species, prob_species, bestHit_similarity, bestHit)

protaxout_swarm_12S_all <- protaxout_swarm_12S_class %>% 
    left_join(protaxout_swarm_12S_order) %>% 
    left_join(protaxout_swarm_12S_family) %>% 
    left_join(protaxout_swarm_12S_genus) %>% 
    left_join(protaxout_swarm_12S_species) 
protaxout_swarm_12S_all$protaxmod <- "unweighted"

```

```{r combine weighted swarm_16S}
pathtoprotaxout <- "~/src/screenforbio-mbc-ailaoshan/"
pathtoprotax2 <- "w_protaxout_swarm_20190624_16S"
pathtoprotax_file <- "16S_otu_table_swarm_lulu_20190624.fas."

w_protaxout_swarm_16S_class <- read_tsv(file.path(pathtoprotaxout, pathtoprotax2, paste0(pathtoprotax_file, "w_class_probs")), col_names = c("queryID", "taxID", "log_prob", "level", "class")) %>% 
    mutate(prob_class = exp(log_prob)) %>% 
    select(queryID, class, prob_class)
w_protaxout_swarm_16S_order <- read_tsv(file.path(pathtoprotaxout, pathtoprotax2, paste0(pathtoprotax_file, "w_order_probs")), col_names = c("queryID", "taxID", "log_prob", "level", "order")) %>% 
    mutate(prob_order = exp(log_prob)) %>% 
    select(queryID, order, prob_order)
w_protaxout_swarm_16S_family <- read_tsv(file.path(pathtoprotaxout, pathtoprotax2, paste0(pathtoprotax_file, "w_family_probs")), col_names = c("queryID", "taxID", "log_prob", "level", "family")) %>% 
    mutate(prob_family = exp(log_prob)) %>% 
    select(queryID, family, prob_family)
w_protaxout_swarm_16S_genus <- read_tsv(file.path(pathtoprotaxout, pathtoprotax2, paste0(pathtoprotax_file, "w_genus_probs")), col_names = c("queryID", "taxID", "log_prob", "level", "genus")) %>% 
    mutate(prob_genus = exp(log_prob)) %>% 
    select(queryID, genus, prob_genus)
w_protaxout_swarm_16S_species <- read.delim(file.path(pathtoprotaxout, pathtoprotax2, paste0(pathtoprotax_file, "w_species_probs_sim")), stringsAsFactors = FALSE, sep = " ", col.names = c("queryID", "taxID", "log_prob", "level", "species", "bestHit_similarity", "bestHit")) %>% 
    mutate(prob_species = exp(log_prob)) %>% 
    mutate(taxID = na_if(taxID, "")) %>% 
    mutate(species = na_if(species, "")) %>% 
    select(queryID, species, prob_species, bestHit_similarity, bestHit)

w_protaxout_swarm_16S_all <- w_protaxout_swarm_16S_class %>% 
    left_join(w_protaxout_swarm_16S_order) %>% 
    left_join(w_protaxout_swarm_16S_family) %>% 
    left_join(w_protaxout_swarm_16S_genus) %>% 
    left_join(w_protaxout_swarm_16S_species) 
w_protaxout_swarm_16S_all$protaxmod <- "weighted"

```

```{r combine unweighted swarm_16S}
pathtoprotaxout <- "~/src/screenforbio-mbc-ailaoshan"
pathtoprotax2 <- "protaxout_swarm_20190624_16S"
pathtoprotax_file <- "16S_otu_table_swarm_lulu_20190624.fas."

protaxout_swarm_16S_class <- read_tsv(file.path(pathtoprotaxout, pathtoprotax2, paste0(pathtoprotax_file, "class_probs")), col_names = c("queryID", "taxID", "log_prob", "level", "class")) %>% 
    mutate(prob_class = exp(log_prob)) %>% 
    select(queryID, class, prob_class)
protaxout_swarm_16S_order <- read_tsv(file.path(pathtoprotaxout, pathtoprotax2, paste0(pathtoprotax_file, "order_probs")), col_names = c("queryID", "taxID", "log_prob", "level", "order")) %>% 
    mutate(prob_order = exp(log_prob)) %>% 
    select(queryID, order, prob_order)
protaxout_swarm_16S_family <- read_tsv(file.path(pathtoprotaxout, pathtoprotax2, paste0(pathtoprotax_file, "family_probs")), col_names = c("queryID", "taxID", "log_prob", "level", "family")) %>% 
    mutate(prob_family = exp(log_prob)) %>% 
    select(queryID, family, prob_family)
protaxout_swarm_16S_genus <- read_tsv(file.path(pathtoprotaxout, pathtoprotax2, paste0(pathtoprotax_file, "genus_probs")), col_names = c("queryID", "taxID", "log_prob", "level", "genus")) %>% 
    mutate(prob_genus = exp(log_prob)) %>% 
    select(queryID, genus, prob_genus)
protaxout_swarm_16S_species <- read.delim(file.path(pathtoprotaxout, pathtoprotax2, paste0(pathtoprotax_file, "species_probs_sim")), stringsAsFactors = FALSE, sep = " ", col.names = c("queryID", "taxID", "log_prob", "level", "species", "bestHit_similarity", "bestHit")) %>% 
    mutate(prob_species = exp(log_prob)) %>% 
    mutate(taxID = na_if(taxID, "")) %>% 
    mutate(species = na_if(species, "")) %>% 
    select(queryID, species, prob_species, bestHit_similarity, bestHit)

protaxout_swarm_16S_all <- protaxout_swarm_16S_class %>% 
    left_join(protaxout_swarm_16S_order) %>% 
    left_join(protaxout_swarm_16S_family) %>% 
    left_join(protaxout_swarm_16S_genus) %>% 
    left_join(protaxout_swarm_16S_species) 
protaxout_swarm_16S_all$protaxmod <- "unweighted"
```

```{r}
protaxout_swarm_16S_weighted_unweighted <- bind_rows(protaxout_swarm_16S_all, w_protaxout_swarm_16S_all) %>% select(protaxmod, everything()) %>% arrange(queryID)

protaxout_swarm_12S_weighted_unweighted <- bind_rows(protaxout_swarm_12S_all, w_protaxout_swarm_12S_all) %>% select(protaxmod, everything()) %>% arrange(queryID)
```


```{r export tables}
pathtoprotaxout <- "~/src/screenforbio-mbc-ailaoshan"
pathtoprotax2 <- "w_protaxout_swarm"
write_tsv(w_protaxout_swarm_12S_all, file.path(pathtoprotaxout, paste0(pathtoprotax2, "_12S_20190624"),"w_protaxout_swarm_12S_all_20190624.tsv"))
write_tsv(w_protaxout_swarm_16S_all, file.path(pathtoprotaxout, paste0(pathtoprotax2 , "_16S_20190624"),"w_protaxout_swarm_16S_all_20190624.tsv"))
```


# Deprecate

```{r combine usearch_12S, eval=FALSE, include=FALSE}
pathtoprotaxout <- "~/src/screenforbio-mbc-ailaoshan/"
pathtoprotax2 <- "w_protaxout_swarm_20190624_16S"
pathtoprotax_file <- "16S_otu_table_swarm_lulu_20190624.fas."
w_protaxout_swarm_12S_class <- read_tsv(file.path(pathtoprotaxout, pathtoprotax2, paste0(pathtoprotax_file, "w_class_probs")), col_names = c("queryID", "taxID", "log_prob", "level", "class")) %>% 

w_protaxout_usearch_12S_class <- read_tsv(file.path(pathtoprotaxout, pathtoprotax2, paste0(pathtoprotax_file, "w_class_probs")), col_names = c("queryID", "taxID", "log_prob", "level", "class")) %>% 
    mutate(prob_class = exp(log_prob)) %>% 
    select(queryID, class, prob_class)

w_protaxout_usearch_12S_order <- read_tsv(file.path(pathtoprotaxout, "w_protaxout_usearch_12S", paste0("all_12S_20180317_otu_table_usearchderep_lulu.", "w_order_probs")), col_names = c("queryID", "taxID", "log_prob", "level", "order")) %>% 
    mutate(prob_order = exp(log_prob)) %>% 
    select(queryID, order, prob_order)
w_protaxout_usearch_12S_family <- read_tsv(file.path(pathtoprotaxout, "w_protaxout_usearch_12S", paste0("all_12S_20180317_otu_table_usearchderep_lulu.", "w_family_probs")), col_names = c("queryID", "taxID", "log_prob", "level", "family")) %>% 
    mutate(prob_family = exp(log_prob)) %>% 
    select(queryID, family, prob_family)
w_protaxout_usearch_12S_genus <- read_tsv(file.path(pathtoprotaxout, "w_protaxout_usearch_12S", paste0("all_12S_20180317_otu_table_usearchderep_lulu.", "w_genus_probs")), col_names = c("queryID", "taxID", "log_prob", "level", "genus")) %>% 
    mutate(prob_genus = exp(log_prob)) %>% 
    select(queryID, genus, prob_genus)
w_protaxout_usearch_12S_species <- read.delim(file.path(pathtoprotaxout, "w_protaxout_usearch_12S", paste0("all_12S_20180317_otu_table_usearchderep_lulu.", "w_species_probs_sim")), stringsAsFactors = FALSE, sep = " ", col.names = c("queryID", "taxID", "log_prob", "level", "species", "bestHit_similarity", "bestHit")) %>% 
    mutate(prob_species = exp(log_prob)) %>% 
    mutate(taxID = na_if(taxID, "")) %>% 
    mutate(species = na_if(species, "")) %>% 
    select(queryID, species, prob_species, bestHit_similarity, bestHit)

w_protaxout_usearch_12S_all <- w_protaxout_usearch_12S_class %>% 
    left_join(w_protaxout_usearch_12S_order) %>% 
    left_join(w_protaxout_usearch_12S_family) %>% 
    left_join(w_protaxout_usearch_12S_genus) %>% 
    left_join(w_protaxout_usearch_12S_species) 
```

